Repository Argo-swe/Docs, pull requests merged in 2024-07, with the labels that each got.

#132 Consuntivo Sprint 6
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-6/budget_speso.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-6/copertura_oraria.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-6/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-6/distribuzione_ore_ruolo.pdf
Labels: responsabile

#126 Aggiunta sezione test al PdQ
  sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/2_RTB/PianoDiQualifica/PianoDiQualifica.tex
  sources/documents/2_RTB/PianoDiQualifica/cruscotto_valutazione.tex
  sources/documents/2_RTB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/analisi_requisiti.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/codifica.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/documentazione.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/errori_formali.tex
  sources/documents/2_RTB/PianoDiQualifica/test/test_accettazione.tex
  sources/documents/2_RTB/PianoDiQualifica/test/test_integrazione.tex
  sources/documents/2_RTB/PianoDiQualifica/test/test_sistema.tex
  sources/documents/2_RTB/PianoDiQualifica/test/test_unita.tex
  sources/documents/2_RTB/PianoDiQualifica/testing.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/frequenza-pull-request.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/variazione-di-costo.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#134 Stesura sezioni "Todo" PdQ
  sources/documents/2_RTB/PianoDiQualifica/PianoDiQualifica.tex
  sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
  sources/documents/2_RTB/PianoDiQualifica/obiettivi_qualita.tex
  sources/documents/2_RTB/PianoDiQualifica/registro_modifiche.tex
  sources/model/global.tex
  sources/model/layout.tex
Labels: documentazione, amministratore

#138 aggiornata struttura UC in NdP
  sources/documents/2_RTB/NormeDiProgetto/Primari/fornitura.tex
Labels: documentazione, amministratore

#136 Revisione struttura metriche
  sources/documents/2_RTB/PianoDiQualifica/PianoDiQualifica.tex
  sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
  sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_per_obiettivo.tex
  sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_processo.tex
  sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_prodotto.tex
  sources/documents/2_RTB/PianoDiQualifica/obiettivi_qualita.tex
  sources/documents/2_RTB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M1.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M2.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M3.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M4.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/errori_formali.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#141 Fix tabella stima costi [PdP]
  sources/documents/2_RTB/PianoDiProgetto/stima_costi.tex
Labels: documentazione, hotfix

#142 Pianificazione e preventivo sprint 8
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-8.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/2_RTB/PianoDiProgetto/PianoDiProgetto.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-8.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-8/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-8/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-06-07/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-06-07/todo.tex
  sources/model/global.tex
Labels: documentazione

#133 Verbale interno del 14 giugno
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-14/VerbaleInterno_2024-06-14.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-14/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-14/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-14/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-14/firma_interna.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-14/local.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-14/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-14/todo.tex
Labels: documentazione

#135 aggiunta pianificazione e preventivo sprint 7
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-7.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-7.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-7/budget_speso.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-7/copertura_oraria.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-7/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-7/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-7/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-7/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#143 Verbale Interno 2024-07-06
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-06/VerbaleInterno_2024-07-06.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-06/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-06/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-06/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-06/firma_interna.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-06/local.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-06/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-06/todo.tex
  sources/model/modelassets/signatures/firma_mattia.png
Labels: documentazione

#152 Rischi gestiti correttamente e sezione rischi consuntivo 2
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
Labels: documentazione

#137 [ALL] Completamento glossario
  sources/documents/2_RTB/Glossario/Glossario.tex
  sources/documents/2_RTB/Glossario/Lettere/a.tex
  sources/documents/2_RTB/Glossario/Lettere/b.tex
  sources/documents/2_RTB/Glossario/Lettere/c.tex
  sources/documents/2_RTB/Glossario/Lettere/d.tex
  sources/documents/2_RTB/Glossario/Lettere/e.tex
  sources/documents/2_RTB/Glossario/Lettere/f.tex
  sources/documents/2_RTB/Glossario/Lettere/g.tex
  sources/documents/2_RTB/Glossario/Lettere/h.tex
  sources/documents/2_RTB/Glossario/Lettere/i.tex
  sources/documents/2_RTB/Glossario/Lettere/j.tex
  sources/documents/2_RTB/Glossario/Lettere/k.tex
  sources/documents/2_RTB/Glossario/Lettere/l.tex
  sources/documents/2_RTB/Glossario/Lettere/m.tex
  sources/documents/2_RTB/Glossario/Lettere/n.tex
  sources/documents/2_RTB/Glossario/Lettere/o.tex
  sources/documents/2_RTB/Glossario/Lettere/p.tex
  sources/documents/2_RTB/Glossario/Lettere/q.tex
  sources/documents/2_RTB/Glossario/Lettere/r.tex
  sources/documents/2_RTB/Glossario/Lettere/s.tex
  sources/documents/2_RTB/Glossario/Lettere/t.tex
  sources/documents/2_RTB/Glossario/Lettere/u.tex
  sources/documents/2_RTB/Glossario/Lettere/v.tex
  sources/documents/2_RTB/Glossario/Lettere/w.tex
  sources/documents/2_RTB/Glossario/Lettere/y.tex
  sources/documents/2_RTB/Glossario/altro.tex
  sources/documents/2_RTB/Glossario/registro_modifiche.tex
  sources/documents/2_RTB/NormeDiProgetto/Primari/fornitura.tex
  sources/documents/2_RTB/NormeDiProgetto/Primari/sviluppo.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/capitolo-riunione.tex
  sources/model/global.tex
Labels: documentazione

#147 Verbale Esterno 2024-07-09
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/VerbaleEsterno_2024-07-09.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/firma_esterna.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/local.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/todo.tex
Labels: documentazione

#155 Approvazione e aggiornamento versione Glossario
  sources/documents/2_RTB/Glossario/local.tex
  sources/documents/2_RTB/Glossario/registro_modifiche.tex
  sources/model/global.tex
Labels: amministratore

#123 Revisione requisiti funzionali [AdR]
  sources/documents/2_RTB/AnalisiDeiRequisiti/AnalisiDeiRequisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/attori.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/debug.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/gestione_dizionari.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc1_1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc20.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc25.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc25_1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc25_1_1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc26.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc31.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc37.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc38.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc5.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/casiduso.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/descrizione.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/introduzione.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/local.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc1.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc10.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc11.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc12.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc13.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc14.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc16.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc17.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc18.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc19.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc2.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc20.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc21.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc22.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc23.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc24.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc25.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc26.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc27.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc28.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc29.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc30.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc31.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc32.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc33.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc34.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc35.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc37.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc38.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc39.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc4.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc40.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc5.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc6.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc8.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc9.tex
  sources/model/global.tex
  sources/model/layout.tex
Labels: documentazione, analista

#148 rischi gestiti correttamente consuntivi
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_tecnologici/RT/RT3.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
Labels: documentazione

#140 Cruscotto di valutazione della qualità
  sources/documents/2_RTB/PianoDiQualifica/assets/efficienza_contromisure.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/efficienza_temporale.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/frequenza_pull_request.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/indice_gulpease.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/metriche_soddisfatte.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/rischi_inattesi.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/stabilita_requisiti.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/stabilità_requisiti.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/stima_a_finire.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/variazione_budget.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/variazione_costo.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/variazione_task_completati.pdf
  sources/documents/2_RTB/PianoDiQualifica/cruscotto_valutazione.tex
  sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
  sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_per_obiettivo.tex
  sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_processo.tex
  sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_prodotto.tex
  sources/documents/2_RTB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/analisi_requisiti.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/codifica.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/errori_formali.tex
  sources/documents/2_RTB/PianoDiQualifica/test/checklist/struttura_documentazione.tex
  sources/documents/2_RTB/PianoDiQualifica/test/test_accettazione.tex
  sources/documents/2_RTB/PianoDiQualifica/test/test_sistema.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/efficienza_contromisure.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/efficienza_temporale.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/frequenza_pull_request.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/indice_gulpease.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/metriche_soddisfatte.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/rischi_inattesi.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/stabilita_requisiti.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/stabilità_requisiti.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/stima_a_finire.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/variazione_budget.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/variazione_di_costo.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/variazione_task_completati.tex
  sources/model/global.tex
Labels: documentazione

#161 Aggiornamento Glossario [introduzione + un termine]
  sources/documents/2_RTB/Glossario/Glossario.tex
  sources/documents/2_RTB/Glossario/Lettere/t.tex
  sources/documents/2_RTB/Glossario/introduzione.tex
  sources/documents/2_RTB/Glossario/local.tex
  sources/documents/2_RTB/Glossario/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#160 Stesura verbale del 2024-07-18
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/VerbaleInterno_2024-07-18.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/firma_interna.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/local.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/todo.tex
Labels: documentazione

#164 Ampliare analisi posteriori s6 s7
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
Labels: documentazione

#166 Stesa pianificazione futura sprint 4
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-4.tex
Labels: documentazione

#163 Consuntivo sprint 9
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO5.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/analisi_rischi.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-8.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-9.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-9/budget_speso.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-9/copertura_oraria.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-9/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-9/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Totale/distribuzione_ore_ruolo.pdf
Labels: documentazione, responsabile

#162 Aggiornamento AdR [post-RTB]
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc19.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc1_1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc3.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc5.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc1.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc13.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc19.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc2.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc20.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc3.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc33.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc36.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc5.tex
  sources/model/global.tex
Labels: documentazione, hotfix

#169 Feature pdp preventivo 10
  sources/documents/2_RTB/NormeDiProgetto/Primari/sviluppo.tex
  sources/documents/2_RTB/NormeDiProgetto/Supporto/documentazione.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO1.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO2.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO4.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO5.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO6.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_tecnologici/RT/RT1.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_tecnologici/RT/RT5.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-8.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-9.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-10.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-9.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-10.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-7.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-8.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-9.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Pianificazione/Sprint-10/gantt.png
  sources/documents/2_RTB/PianoDiProgetto/assets/Pianificazione/Sprint-9/gantt.png
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-10/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-10/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/stimatemporale.png
  sources/documents/2_RTB/PianoDiProgetto/modello_sviluppo.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiProgetto/stima_costi.tex
  sources/documents/2_RTB/PianoDiProgetto/stima_temporale.tex
  sources/model/global.tex
Labels: documentazione, responsabile

#170 Rilascio documenti
  sources/documents/2_RTB/LetteraDiPresentazione/Presentazione_2/Presentazione_2.tex
  sources/documents/2_RTB/LetteraDiPresentazione/Presentazione_2/local.tex
  sources/documents/2_RTB/NormeDiProgetto/local.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiProgetto/local.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiQualifica/local.tex
  sources/documents/2_RTB/PianoDiQualifica/registro_modifiche.tex
  sources/model/global.tex
Labels: responsabile

#171 Fix firma
  sources/documents/2_RTB/LetteraDiPresentazione/Presentazione_2/Presentazione_2.tex
Labels: hotfix

#172 Struttura documento Specifica Tecnica
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO5.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/introduzione.tex
  sources/documents/2_RTB/PianoDiProgetto/stima_costi.tex
  sources/documents/2_RTB/PianoDiProgetto/stima_temporale.tex
  sources/documents/3_PB/ManualeUtente/ManualeUtente.tex
  sources/documents/3_PB/ManualeUtente/assets/.gitkeep
  sources/documents/3_PB/ManualeUtente/installazione_avvio.tex
  sources/documents/3_PB/ManualeUtente/introduzione.tex
  sources/documents/3_PB/ManualeUtente/istruzioni_utilizzo.tex
  sources/documents/3_PB/ManualeUtente/local.tex
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/requisiti_sistema.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/architettura.tex
  sources/documents/3_PB/SpecificaTecnica/SpecificaTecnica.tex
  sources/documents/3_PB/SpecificaTecnica/assets/.gitkeep
  sources/documents/3_PB/SpecificaTecnica/introduzione.tex
  sources/documents/3_PB/SpecificaTecnica/local.tex
  sources/documents/3_PB/SpecificaTecnica/registro_modifiche.tex
  sources/documents/3_PB/SpecificaTecnica/tecnologie.tex
  sources/model/global.tex
Labels: documentazione, progettista

#173 Verbale Interno 2024-07-26
  sources/documents/2_RTB/AnalisiDeiRequisiti/introduzione.tex
  sources/documents/2_RTB/NormeDiProgetto/Primari/fornitura.tex
  sources/documents/2_RTB/NormeDiProgetto/Primari/sviluppo.tex
  sources/documents/2_RTB/NormeDiProgetto/Supporto/documentazione.tex
  sources/documents/2_RTB/NormeDiProgetto/introduzione.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_personali/RP/RP1.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-8.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-9.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-7.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-8.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-9.tex
  sources/documents/2_RTB/PianoDiProgetto/introduzione.tex
  sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
  sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_prodotto.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/VerbaleInterno_2024-07-26.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/assets/.gitkeep
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/capitolo-informazioni.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/capitolo-riunione.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/firma_interna.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/local.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/registro_modifiche.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/todo.tex
Labels: documentazione, hotfix

#174 Aggiornamento script compilazione (post RTB)
  .github/workflows/build.yml
Labels: task, amministratore

#175 Progettazione front-end
  sources/documents/3_PB/SpecificaTecnica/Architettura/Frontend/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/architettura.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/frontend.tex
  sources/documents/3_PB/SpecificaTecnica/assets/.gitkeep
  sources/documents/3_PB/SpecificaTecnica/assets/Frontend/architettura_mvvm.png
  sources/documents/3_PB/SpecificaTecnica/assets/Frontend/overview_mvvm.png
  sources/documents/3_PB/SpecificaTecnica/assets/architettura_web_app.pdf
  sources/documents/3_PB/SpecificaTecnica/assets/client_server.png
Labels: documentazione, progettista

#176 Struttura cartelle front-end
  sources/documents/3_PB/SpecificaTecnica/Architettura/Backend/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/Backend/struttura.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/Frontend/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/Frontend/struttura.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/architettura.tex
  sources/model/layout.tex
Labels: documentazione, progettista

#177 Progettazione componenti front-end
  .gitignore
  sources/documents/3_PB/SpecificaTecnica/Architettura/Frontend/struttura.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/architettura.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/frontend.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Backend/componenti.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Frontend/componenti.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/SpecificaTecnica.tex
  sources/documents/3_PB/SpecificaTecnica/registro_modifiche.tex
  sources/documents/3_PB/SpecificaTecnica/tecnologie.tex
  sources/model/global.tex
Labels: documentazione, progettista
