Repository Argo-swe/Docs, pull requests merged in 2024-09, with the labels that each got.

#211 Stesura verbale interno 2024-08-27
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-27/VerbaleInterno_2024-08-27.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-27/assets/.gitkeep
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-27/capitolo-informazioni.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-27/capitolo-riunione.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-27/firma_interna.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-27/local.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-27/registro_modifiche.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-27/todo.tex
Labels: documentazione

#210 Debugger manuale utente
  sources/documents/3_PB/ManualeUtente/assets/analisi_debug1.jpg
  sources/documents/3_PB/ManualeUtente/assets/analisi_debug2.jpg
  sources/documents/3_PB/ManualeUtente/assets/tasto_close_debug.png
  sources/documents/3_PB/ManualeUtente/assets/tasto_dawnload_debug.png
  sources/documents/3_PB/ManualeUtente/assets/tasto_info_debug.png
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
  sources/model/global.tex
Labels: documentazione

#207 Revisione e tracciamento requisiti AdR
  sources/documents/3_PB/AnalisiDeiRequisiti/assets/uc36.png
  sources/documents/3_PB/AnalisiDeiRequisiti/assets/uc37.png
  sources/documents/3_PB/AnalisiDeiRequisiti/assets/uc38.png
  sources/documents/3_PB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/3_PB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/3_PB/AnalisiDeiRequisiti/usecase/uc32.tex
  sources/documents/3_PB/AnalisiDeiRequisiti/usecase/uc36.tex
  sources/documents/3_PB/AnalisiDeiRequisiti/usecase/uc37.tex
  sources/documents/3_PB/AnalisiDeiRequisiti/usecase/uc38.tex
  sources/model/global.tex
Labels: documentazione, task

#212 Consuntivo sprint 12
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-12.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-12/budget_speso.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-12/copertura_oraria.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-12/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-12/distribuzione_ore_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/3_PB/PianoDiProgetto/stima_costi.tex
  sources/model/global.tex
Labels: documentazione

#213 Pianificazione e preventivo sprint 13
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/Sprint/sprint-13.tex
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/3_PB/PianoDiProgetto/Preventivo/Sprint/sprint-13.tex
  sources/documents/3_PB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/3_PB/PianoDiProgetto/assets/Pianificazione/Sprint-13/gantt.PNG
  sources/documents/3_PB/PianoDiProgetto/assets/Preventivo/Sprint-13/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Preventivo/Sprint-13/distribuzione_ore_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#208 Aggiornamento test [PdQ]
  sources/documents/3_PB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/3_PB/PianoDiQualifica/test/checklist/codifica.tex
  sources/documents/3_PB/PianoDiQualifica/test/test_accettazione.tex
  sources/documents/3_PB/PianoDiQualifica/test/test_integrazione.tex
  sources/documents/3_PB/PianoDiQualifica/test/test_sistema.tex
  sources/documents/3_PB/PianoDiQualifica/test/test_unita.tex
  sources/model/global.tex
Labels: documentazione, amministratore, programmatore, progettista

#215 verbale esterno 09/09
  sources/documents/3_PB/Verbali/Esterni/VerbaleEsterno_2024-09-09/VerbaleEsterno_2024-09-09.tex
  sources/documents/3_PB/Verbali/Esterni/VerbaleEsterno_2024-09-09/assets/.gitkeep
  sources/documents/3_PB/Verbali/Esterni/VerbaleEsterno_2024-09-09/capitolo-informazioni.tex
  sources/documents/3_PB/Verbali/Esterni/VerbaleEsterno_2024-09-09/capitolo-riunione.tex
  sources/documents/3_PB/Verbali/Esterni/VerbaleEsterno_2024-09-09/firma_esterna.tex
  sources/documents/3_PB/Verbali/Esterni/VerbaleEsterno_2024-09-09/local.tex
  sources/documents/3_PB/Verbali/Esterni/VerbaleEsterno_2024-09-09/registro_modifiche.tex
  sources/documents/3_PB/Verbali/Esterni/VerbaleEsterno_2024-09-09/todo.tex
Labels: documentazione

#218 Rilascio Analisi dei Requisiti v2.0.0
  sources/documents/3_PB/AnalisiDeiRequisiti/local.tex
  sources/documents/3_PB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/3_PB/AnalisiDeiRequisiti/requisiti.tex
  sources/model/global.tex
Labels: documentazione, responsabile

#219 Aggiornato PdQ a ultime modifiche test
  sources/documents/3_PB/PianoDiQualifica/test/test_unita.tex
Labels: documentazione, amministratore

#206 Aggiornamento termini Glossario
  sources/documents/3_PB/Glossario/Lettere/b.tex
  sources/documents/3_PB/Glossario/Lettere/c.tex
  sources/documents/3_PB/Glossario/Lettere/d.tex
  sources/documents/3_PB/Glossario/Lettere/e.tex
  sources/documents/3_PB/Glossario/Lettere/g.tex
  sources/documents/3_PB/Glossario/Lettere/j.tex
  sources/documents/3_PB/Glossario/Lettere/k.tex
  sources/documents/3_PB/Glossario/Lettere/l.tex
  sources/documents/3_PB/Glossario/Lettere/m.tex
  sources/documents/3_PB/Glossario/Lettere/n.tex
  sources/documents/3_PB/Glossario/Lettere/o.tex
  sources/documents/3_PB/Glossario/Lettere/p.tex
  sources/documents/3_PB/Glossario/Lettere/r.tex
  sources/documents/3_PB/Glossario/Lettere/s.tex
  sources/documents/3_PB/Glossario/Lettere/t.tex
  sources/documents/3_PB/Glossario/Lettere/u.tex
  sources/documents/3_PB/Glossario/Lettere/v.tex
  sources/documents/3_PB/Glossario/Lettere/w.tex
  sources/documents/3_PB/Glossario/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/sezione_utente.tex
  sources/documents/3_PB/NormeDiProgetto/Organizzativi/gestione.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/revisionecongiunta.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/Sprint/sprint-2.tex
  sources/model/global.tex
Labels: documentazione, task

#221 Consuntivo sprint 13
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-13.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-13/budget_speso.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-13/copertura_oraria.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-13/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-13/distribuzione_ore_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/3_PB/PianoDiProgetto/stima_costi.tex
  sources/model/global.tex
Labels: documentazione

#222 Pianificazione e preventivo sprint 14
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/Sprint/sprint-14.tex
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/3_PB/PianoDiProgetto/Preventivo/Sprint/sprint-14.tex
  sources/documents/3_PB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/3_PB/PianoDiProgetto/assets/Pianificazione/Sprint-14/gantt.png
  sources/documents/3_PB/PianoDiProgetto/assets/Preventivo/Sprint-14/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Preventivo/Sprint-14/distribuzione_ore_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#228 Verbale Interno 2024-09-08
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-09-08/VerbaleInterno_2024-09-08.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-09-08/assets/.gitkeep
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-09-08/capitolo-informazioni.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-09-08/capitolo-riunione.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-09-08/firma_interna.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-09-08/local.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-09-08/registro_modifiche.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-09-08/todo.tex
Labels: documentazione

#227 Aggiornamento grafici PdQ
  sources/documents/3_PB/PianoDiQualifica/assets/adeguatezza_funzioni.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/code_coverage.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/complessita_ciclomatica.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/completezza_descrittiva.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/efficacia_contromisure.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/efficienza_temporale.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/frequenza_pull_request.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/impatto_modifiche.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/indice_gulpease.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/linee_medie_codice.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/metriche_soddisfatte.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/requisiti_desiderabili_soddisfatti.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/requisiti_obbligatori_soddisfatti.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/requisiti_opzionali_soddisfatti.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/rimozione_difetti.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/rischi_inattesi.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/stabilita_requisiti.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/stima_a_finire.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/test_superati.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/tolleranza_errori.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/variazione_budget.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/variazione_task_completati.pdf
  sources/documents/3_PB/PianoDiQualifica/grafici.tex
  sources/documents/3_PB/PianoDiQualifica/introduzione.tex
  sources/documents/3_PB/PianoDiQualifica/obiettivi_qualita.tex
  sources/documents/3_PB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/browser_supportati.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/efficienza_temporale.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/impatto_modifiche.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/indice_gulpease.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/metriche_codice.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/tolleranza_errori.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/variazione_budget.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/variazione_task_completati.tex
  sources/model/global.tex
Labels: documentazione

#220 Aggiornamento Manuale Utente
  sources/documents/3_PB/ManualeUtente/ManualeUtente.tex
  sources/documents/3_PB/ManualeUtente/assets/.gitkeep
  sources/documents/3_PB/ManualeUtente/assets/settings_topbar.png
  sources/documents/3_PB/ManualeUtente/avvio.tex
  sources/documents/3_PB/ManualeUtente/funzionalita_generali.tex
  sources/documents/3_PB/ManualeUtente/installazione.tex
  sources/documents/3_PB/ManualeUtente/installazione_avvio.tex
  sources/documents/3_PB/ManualeUtente/introduzione.tex
  sources/documents/3_PB/ManualeUtente/istruzioni_utilizzo.tex
  sources/documents/3_PB/ManualeUtente/mobile.tex
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/requisiti_sistema.tex
  sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
  sources/documents/3_PB/ManualeUtente/sezione_utente.tex
  sources/documents/3_PB/ManualeUtente/utilizzo_chat.tex
  sources/documents/3_PB/ManualeUtente/workflow.tex
  sources/model/global.tex
Labels: documentazione

#226 Aggiornamento Norme di Progetto
  sources/documents/3_PB/NormeDiProgetto/Primari/fornitura.tex
  sources/documents/3_PB/NormeDiProgetto/Primari/sviluppo.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_10.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_13.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_14.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_15.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_16.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_17.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_18.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_19.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_20.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/Accertamento_qualita/Metriche/metriche_prodotto/M_PD_21.tex
  sources/documents/3_PB/NormeDiProgetto/Supporto/gestioneconfigurazione.tex
  sources/documents/3_PB/NormeDiProgetto/introduzione.tex
  sources/documents/3_PB/NormeDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#229 Rilascio Glossario
  sources/documents/3_PB/Glossario/local.tex
  sources/documents/3_PB/Glossario/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#233 Rilascio Manuale Utente
  sources/documents/3_PB/ManualeUtente/assets/analisi_debug.png
  sources/documents/3_PB/ManualeUtente/assets/analisi_debug1.jpg
  sources/documents/3_PB/ManualeUtente/assets/analisi_debug2.jpg
  sources/documents/3_PB/ManualeUtente/assets/chat_example.png
  sources/documents/3_PB/ManualeUtente/assets/chat_generale.png
  sources/documents/3_PB/ManualeUtente/assets/copia.png
  sources/documents/3_PB/ManualeUtente/assets/dd_confirm_delete.png
  sources/documents/3_PB/ManualeUtente/assets/dd_list.png
  sources/documents/3_PB/ManualeUtente/assets/elimina_chat.png
  sources/documents/3_PB/ManualeUtente/assets/es_chat_errore.png
  sources/documents/3_PB/ManualeUtente/assets/mobile.png
  sources/documents/3_PB/ManualeUtente/assets/scroll_chat.PNG
  sources/documents/3_PB/ManualeUtente/assets/tasto_close_debug.png
  sources/documents/3_PB/ManualeUtente/assets/tasto_dawnload_debug.png
  sources/documents/3_PB/ManualeUtente/assets/tasto_download_debug.PNG
  sources/documents/3_PB/ManualeUtente/assets/text_box_arrow.png
  sources/documents/3_PB/ManualeUtente/funzionalita_generali.tex
  sources/documents/3_PB/ManualeUtente/installazione.tex
  sources/documents/3_PB/ManualeUtente/introduzione.tex
  sources/documents/3_PB/ManualeUtente/istruzioni_utilizzo.tex
  sources/documents/3_PB/ManualeUtente/local.tex
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/requisiti_sistema.tex
  sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
  sources/documents/3_PB/ManualeUtente/sezione_utente.tex
  sources/documents/3_PB/PianoDiQualifica/test/test_unita.tex
  sources/model/global.tex
Labels: documentazione

#225 Lettera di Presentazione (seconda parte)
  sources/documents/3_PB/LetteraDiPresentazione/Presentazione_2/Presentazione_2.tex
  sources/documents/3_PB/LetteraDiPresentazione/Presentazione_2/local.tex
Labels: documentazione

#234 Hotfix lettera
  sources/documents/3_PB/LetteraDiPresentazione/Presentazione_2/local.tex
Labels: documentazione, hotfix
