Repository Argo-swe/Docs, pull requests merged in 2024-08, with the labels that each got.

#179 Verbale interno 2024-08-01
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/capitolo-riunione.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-07-26/todo.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-01/VerbaleInterno_2024-08-01.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-01/assets/.gitkeep
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-01/capitolo-informazioni.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-01/capitolo-riunione.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-01/firma_interna.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-01/local.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-01/registro_modifiche.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-01/todo.tex
Labels: documentazione

#182 ARGO-256-Stesura-manuale-utente-gestione-dizionari-dati
  sources/documents/3_PB/ManualeUtente/assets/dd_confirm_delete.png
  sources/documents/3_PB/ManualeUtente/assets/dd_create_button.png
  sources/documents/3_PB/ManualeUtente/assets/dd_delete_button.png
  sources/documents/3_PB/ManualeUtente/assets/dd_download_button.png
  sources/documents/3_PB/ManualeUtente/assets/dd_edit_button.png
  sources/documents/3_PB/ManualeUtente/assets/dd_edit_metadata_button.png
  sources/documents/3_PB/ManualeUtente/assets/dd_list.png
  sources/documents/3_PB/ManualeUtente/assets/dd_modal_create.png
  sources/documents/3_PB/ManualeUtente/assets/login_modal.png
  sources/documents/3_PB/ManualeUtente/assets/login_topbar.png
  sources/documents/3_PB/ManualeUtente/assets/user_icon.png
  sources/documents/3_PB/ManualeUtente/istruzioni_utilizzo.tex
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
Labels: documentazione

#181 Aggiornamento tecnologie in Specifica Tecnica [pytest]
  sources/documents/3_PB/SpecificaTecnica/Architettura/Backend/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/Frontend/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/componenti.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Frontend/componenti.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/progettazione_dettaglio.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/tecnologie.tex
Labels: documentazione, progettista

#185 Aggiunte motivazioni per Jest
  sources/documents/3_PB/SpecificaTecnica/tecnologie.tex
Labels: documentazione, progettista

#183 Sezione DataBase - di specifiche tecniche
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/assets/Database/DiagrammiDB.pdf
  sources/documents/3_PB/SpecificaTecnica/assets/Database/DiagrammiDB.png
  sources/documents/3_PB/SpecificaTecnica/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#180 Progettazione di dettaglio front-end - Parte 1
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Frontend/componenti.tex
  sources/documents/3_PB/SpecificaTecnica/SpecificaTecnica.tex
Labels: documentazione, progettista

#189 Sezione modello esagonale
  sources/documents/3_PB/SpecificaTecnica/Architettura/Backend/modello_architettura.tex
  sources/documents/3_PB/SpecificaTecnica/Architettura/Backend/struttura.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/Database/database.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/componenti.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/progettazione_logica.tex
  sources/documents/3_PB/SpecificaTecnica/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, progettista

#184 Impostazioni manuale utente
  sources/documents/3_PB/ManualeUtente/assets/menu_config.png
  sources/documents/3_PB/ManualeUtente/assets/settings_icon.png
  sources/documents/3_PB/ManualeUtente/assets/settings_topbar.png
  sources/documents/3_PB/ManualeUtente/istruzioni_utilizzo.tex
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/sezione_utente.tex
Labels: documentazione, progettista

#187 Consuntivo sprint 10
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-10.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-10/budget_speso.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-10/copertura_oraria.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-10/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-10/distribuzione_ore_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/3_PB/PianoDiProgetto/stima_costi.tex
  sources/model/global.tex
Labels: documentazione

#188 funzionalità utente e impostazioni generali nel manuale utente
  sources/documents/3_PB/ManualeUtente/funzionalita_generali.tex
  sources/documents/3_PB/ManualeUtente/istruzioni_utilizzo.tex
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/utilizzo_chat.tex
Labels: documentazione

#192 manuale utente immagini
  sources/documents/3_PB/ManualeUtente/assets/cambio_dbms.png
  sources/documents/3_PB/ManualeUtente/assets/cambio_dizionariodati.png
  sources/documents/3_PB/ManualeUtente/assets/cambio_lingua.png
  sources/documents/3_PB/ManualeUtente/assets/chat_generale.png
  sources/documents/3_PB/ManualeUtente/assets/copia.png
  sources/documents/3_PB/ManualeUtente/assets/elimina_chat.png
  sources/documents/3_PB/ManualeUtente/assets/es_chat_errore.png
  sources/documents/3_PB/ManualeUtente/assets/info_dizionario.png
  sources/documents/3_PB/ManualeUtente/assets/mostra_menù.png
  sources/documents/3_PB/ManualeUtente/funzionalita_generali.tex
  sources/documents/3_PB/ManualeUtente/istruzioni_utilizzo.tex
  sources/documents/3_PB/ManualeUtente/utilizzo_chat.tex
Labels: documentazione

#191 Manuale utente visualizzazzione versione mobile
  sources/documents/3_PB/ManualeUtente/assets/dd_burger_menu.png
  sources/documents/3_PB/ManualeUtente/assets/dd_kebab_menu.png
  sources/documents/3_PB/ManualeUtente/assets/menu_config.png
  sources/documents/3_PB/ManualeUtente/assets/mobile.png
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/sezione_utente.tex
Labels: documentazione

#193 Preventivo e pianificazione sprint 11
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/Sprint/sprint-11.tex
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/3_PB/PianoDiProgetto/Preventivo/Sprint/sprint-11.tex
  sources/documents/3_PB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/3_PB/PianoDiProgetto/assets/Pianificazione/Sprint-11/gantt.png
  sources/documents/3_PB/PianoDiProgetto/assets/Preventivo/Sprint-11/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Preventivo/Sprint-11/distribuzione_ore_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#190 Aggiunta progettazione alto livello back-end
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Backend/componenti.tex
Labels: documentazione, amministratore

#186 Aggiornamento grafici PdQ [sprint 10]
  sources/documents/3_PB/PianoDiQualifica/assets/code_coverage.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/completezza_descrittiva.pdf.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/efficacia_contromisure.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/efficienza_temporale.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/frequenza_pull_request.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/rischi_inattesi.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/stabilita_requisiti.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/stima_a_finire.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/test_superati.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/variazione_budget.pdf
  sources/documents/3_PB/PianoDiQualifica/assets/variazione_task_completati.pdf
  sources/documents/3_PB/PianoDiQualifica/cruscotto_valutazione.tex
  sources/documents/3_PB/PianoDiQualifica/metriche/tabelle_metriche_prodotto.tex
  sources/documents/3_PB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/accoppiamento_classi.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/accuratezza_risposta.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/adeguatezza_funzioni_sviluppate.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/browser_supportati.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/code_coverage.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/complessita_ciclomatica.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/completezza_descrittiva.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/impatto_modifiche.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/indice_manutenibilita.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/linee_codice_metodo.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/percentuale_test_superati.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/profondita_ampiezza.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/requisiti_desiderabili_soddisfatti.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/requisiti_obbligatori_soddisfatti.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/requisiti_opzionali_soddisfatti.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/rimozione_difetti.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/tempo_apprendimento.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/tempo_risposta.tex
  sources/documents/3_PB/PianoDiQualifica/valutazionemetriche/tolleranza_errori.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#195 Aggiornamento PdQ [template test di unità]
  sources/documents/3_PB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/3_PB/PianoDiQualifica/test/test_unita.tex
  sources/model/global.tex
Labels: documentazione, programmatore, progettista

#194 Progettazione dettaglio front-end + fix progettazione logica
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Frontend/componenti.tex
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Frontend/componenti.tex
Labels: documentazione, progettista

#197 verbale 8/8
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-08/VerbaleInterno_2024-08-08.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-08/assets/.gitkeep
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-08/capitolo-informazioni.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-08/capitolo-riunione.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-08/firma_interna.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-08/local.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-08/registro_modifiche.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-08/todo.tex
Labels: documentazione

#198 Sezione Workflow Manuale utente
  sources/documents/3_PB/ManualeUtente/assets/workflow_1.png
  sources/documents/3_PB/ManualeUtente/assets/workflow_2.png
  sources/documents/3_PB/ManualeUtente/assets/workflow_3.png
  sources/documents/3_PB/ManualeUtente/assets/workflow_4.png
  sources/documents/3_PB/ManualeUtente/assets/workflow_5.png
  sources/documents/3_PB/ManualeUtente/assets/workflow_6.png
  sources/documents/3_PB/ManualeUtente/assets/workflow_7.png
  sources/documents/3_PB/ManualeUtente/registro_modifiche.tex
  sources/documents/3_PB/ManualeUtente/sezione_utente.tex
  sources/model/global.tex
Labels: documentazione, progettista

#199 Aggiornamento test di unità [PdQ]
  sources/documents/3_PB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/3_PB/PianoDiQualifica/test/test_unita.tex
  sources/model/global.tex
Labels: documentazione, programmatore, progettista

#200 Aggiornamento NdP [workflow ChatSQL]
  sources/documents/3_PB/NormeDiProgetto/Supporto/gestioneconfigurazione.tex
  sources/documents/3_PB/NormeDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#201 Consuntivo sprint 11
  .gitignore
  sources/.gitignore
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-1.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-10.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-11.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-4.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-5.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-8.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/Sprint/sprint-9.tex
  sources/documents/3_PB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-11/budget_speso.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-11/copertura_oraria.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-11/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Consuntivo/Sprint-11/distribuzione_ore_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/3_PB/PianoDiProgetto/stima_costi.tex
  sources/model/global.tex
Labels: documentazione

#202 Pianificazione e preventivo sprint 12
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/Sprint/sprint-12.tex
  sources/documents/3_PB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/3_PB/PianoDiProgetto/Preventivo/Sprint/sprint-12.tex
  sources/documents/3_PB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/3_PB/PianoDiProgetto/assets/Pianificazione/Sprint-12/gantt.png
  sources/documents/3_PB/PianoDiProgetto/assets/Preventivo/Sprint-12/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/assets/Preventivo/Sprint-12/distribuzione_ore_ruolo.pdf
  sources/documents/3_PB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#203 Stesura verbale interno 2024-08-19
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-19/VerbaleInterno_2024-08-19.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-19/assets/.gitkeep
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-19/capitolo-informazioni.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-19/capitolo-riunione.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-19/firma_interna.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-19/local.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-19/registro_modifiche.tex
  sources/documents/3_PB/Verbali/Interni/VerbaleInterno_2024-08-19/todo.tex
Labels: documentazione

#209 ST - Stesura tabella tracciamento requisiti routes
  sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Backend/componenti.tex
Labels: documentazione, analista
