Repository Argo-swe/Docs, pull requests merged in 2024-04, with the labels that each got.

#19 Global aggiornato con formato post-candidatura
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, task, amministratore

#21 Caricamento Verbale Interno 2024-04-03
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/capitolo-informazioni.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/firma_interna.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/local.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/registro_modifiche.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/todo.tex
  sources/model/global.tex
  sources/model/modelassets/signatures/firma_riccardo.png
Labels: documentazione, responsabile

#22 Modifica Verbale Interno 2024-04-03
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/capitolo-riunione.tex
Labels: hotfix, responsabile

#31 Approvazione Verbale Interno 2024-04-10
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-10/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-10/local.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-10/registro_modifiche.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-10/todo.tex
Labels: responsabile

#33 Strutturazione Iniziale del PdP
  sources/documents/RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_tecnologici/RT/RT1.tex
  sources/documents/RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_tecnologici/rischi_tecnologici.tex
  sources/documents/RTB/PianoDiProgetto/Analisi_rischi/analisi_rischi.tex
  sources/documents/RTB/PianoDiProgetto/Consuntivo/Periodi/periodo-1.tex
  sources/documents/RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/RTB/PianoDiProgetto/Pianificazione/Periodi/periodo-1.tex
  sources/documents/RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/RTB/PianoDiProgetto/PianoDiProgetto.tex
  sources/documents/RTB/PianoDiProgetto/Preventivo/Periodi/periodo-1.tex
  sources/documents/RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/RTB/PianoDiProgetto/assets/Preventivo/Periodo-1/.gitkeep
  sources/documents/RTB/PianoDiProgetto/introduzione.tex
  sources/documents/RTB/PianoDiProgetto/local.tex
  sources/documents/RTB/PianoDiProgetto/modello_sviluppo.tex
  sources/documents/RTB/PianoDiProgetto/registro_modifiche.tex
Labels: documentazione, responsabile

#45 Modifica container, aggiunta pacchetto fontawesome5, revisione comandi globali
  sources/model/global.tex
  sources/model/layout.tex
  tools/docker/Dockerfile
  tools/docker/install-deps.sh
Labels: task, amministratore

#30 Struttura minima Glossario
  sources/documents/RTB/Glossario/Glossario.tex
  sources/documents/RTB/Glossario/a.tex
  sources/documents/RTB/Glossario/altro.tex
  sources/documents/RTB/Glossario/b.tex
  sources/documents/RTB/Glossario/c.tex
  sources/documents/RTB/Glossario/d.tex
  sources/documents/RTB/Glossario/e.tex
  sources/documents/RTB/Glossario/f.tex
  sources/documents/RTB/Glossario/g.tex
  sources/documents/RTB/Glossario/h.tex
  sources/documents/RTB/Glossario/i.tex
  sources/documents/RTB/Glossario/j.tex
  sources/documents/RTB/Glossario/k.tex
  sources/documents/RTB/Glossario/l.tex
  sources/documents/RTB/Glossario/local.tex
  sources/documents/RTB/Glossario/m.tex
  sources/documents/RTB/Glossario/n.tex
  sources/documents/RTB/Glossario/o.tex
  sources/documents/RTB/Glossario/p.tex
  sources/documents/RTB/Glossario/q.tex
  sources/documents/RTB/Glossario/r.tex
  sources/documents/RTB/Glossario/registro_modifiche.tex
  sources/documents/RTB/Glossario/s.tex
  sources/documents/RTB/Glossario/t.tex
  sources/documents/RTB/Glossario/u.tex
  sources/documents/RTB/Glossario/v.tex
  sources/documents/RTB/Glossario/w.tex
  sources/documents/RTB/Glossario/x.tex
  sources/documents/RTB/Glossario/y.tex
  sources/documents/RTB/Glossario/z.tex
Labels: documentazione, amministratore

#55 Verbale Interno 2024-04-20 + aggiunta sezione glossario [1.3]
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/capitolo-informazioni.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-10/capitolo-informazioni.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-10/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-16/capitolo-informazioni.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/VerbaleInterno_2024-04-20.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/assets/.gitkeep
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/capitolo-informazioni.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/firma_interna.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/local.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/registro_modifiche.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/todo.tex
  sources/model/global.tex
Labels: documentazione

#53 Caricamento Norme di Progetto
  sources/documents/RTB/NormeDiProgetto/NormeDiProgetto.tex
  sources/documents/RTB/NormeDiProgetto/Organizzativi/gestione.tex
  sources/documents/RTB/NormeDiProgetto/Primari/fornitura.tex
  sources/documents/RTB/NormeDiProgetto/Primari/sviluppo.tex
  sources/documents/RTB/NormeDiProgetto/Supporto/documentazione.tex
  sources/documents/RTB/NormeDiProgetto/Supporto/gestioneconfigurazione.tex
  sources/documents/RTB/NormeDiProgetto/Supporto/validazione.tex
  sources/documents/RTB/NormeDiProgetto/Supporto/verifica.tex
  sources/documents/RTB/NormeDiProgetto/assets/.gitkeep
  sources/documents/RTB/NormeDiProgetto/introduzione.tex
  sources/documents/RTB/NormeDiProgetto/local.tex
  sources/documents/RTB/NormeDiProgetto/processi_organizzativi.tex
  sources/documents/RTB/NormeDiProgetto/processi_primari.tex
  sources/documents/RTB/NormeDiProgetto/processi_supporto.tex
  sources/documents/RTB/NormeDiProgetto/registro_modifiche.tex
Labels: documentazione, amministratore

#58 Aggiornamento PdP
  sources/documents/RTB/PianoDiProgetto/Pianificazione/Periodi/periodo-1.tex
  sources/documents/RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-1.tex
  sources/documents/RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-2.tex
  sources/documents/RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/RTB/PianoDiProgetto/PianoDiProgetto.tex
  sources/documents/RTB/PianoDiProgetto/Preventivo/Periodi/periodo-1.tex
  sources/documents/RTB/PianoDiProgetto/Preventivo/Sprint/sprint-1.tex
  sources/documents/RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/RTB/PianoDiProgetto/assets/Preventivo/Periodo-1/.gitkeep
  sources/documents/RTB/PianoDiProgetto/assets/Preventivo/Sprint-1/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/RTB/PianoDiProgetto/assets/Preventivo/Sprint-1/distribuzione_ore_ruolo.pdf
  sources/documents/RTB/PianoDiProgetto/introduzione.tex
  sources/documents/RTB/PianoDiProgetto/local.tex
  sources/documents/RTB/PianoDiProgetto/registro_modifiche.tex
  sources/model/layout.tex
Labels: responsabile
