Repository Argo-swe/Docs, pull requests merged in 2024-06, with the labels that each got.

#96 Stese sezioni 1.1 e 1.3
  sources/documents/2_RTB/PianoDiProgetto/introduzione.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
Labels: documentazione, responsabile

#95 Stesura pianificazione delle attività sprint 4
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
Labels: documentazione, responsabile

#97 Hotfix pdp sprint 1, 2, 3
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-2/budget_speso.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-2/copertura_oraria.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-3/budget_speso.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-3/copertura_oraria.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-3/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-3/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-3/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-3/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/local.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, hotfix, responsabile

#98 Primi punti dell'analisi a posteriori sprint 3
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
Labels: documentazione, responsabile

#81 Metriche di qualità [NdP]
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_1.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_10.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_11.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_12.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_13.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_14.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_15.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_16.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_2.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_3.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_4.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_5.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_6.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_7.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_8.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_9.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_1.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_2.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_3.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_4.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_5.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_6.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_7.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_8.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M3.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M3/M_3_1.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M3/m_3_2.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_1.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_2.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_3.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_intro.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/accertamento_introduzione.tex
  sources/documents/2_RTB/NormeDiProgetto/NormeDiProgetto.tex
  sources/documents/2_RTB/NormeDiProgetto/accertamento_qualita.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/documents/2_RTB/NormeDiProgetto/strumenti.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#99 Aggiunta sezione aggiornamento pianificazione preventivo sprint 3
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
Labels: documentazione, responsabile

#100 Aggiunta gestione dei rischi per sprint 3
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_personali/RP/RP1.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_personali/rischi_personali.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/analisi_rischi.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
Labels: documentazione, responsabile

#101 Aggiornamento metriche
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_17.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_4.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_5.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_6.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_7.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_8.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M3.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M3/M_3_1.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M3/M_3_3.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M3/m_3_2.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_2.tex
  sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_3.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M1.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M2.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M3.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M4.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#105 Aggiornata sezione 5 con grafico
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Totale/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/stima_costi.tex
Labels: documentazione, responsabile

#87 Verbale interno 2024-05-23
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/todo.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/firma_interna.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/local.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/todo.tex
Labels: documentazione

#106 Aggiornamento sezioni consuntivo sprint 2
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#102 Feature ndp aggiornamento sezione adr
  sources/documents/2_RTB/NormeDiProgetto/Primari/fornitura.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
Labels: documentazione

#94 Aggiornamento casi d'uso
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc10.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc18.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc2.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc3.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc4.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc5.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc7.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/casiduso.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/descrizione.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/introduzione.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc1.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc10.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc11.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc12.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc13.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc14.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc15.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc16.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc17.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc18.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc19.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc19_old.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc2.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc20.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc21.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc22.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc23.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc24.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc25.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc3.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc4.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc5.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc6.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc7.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc8.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc9.tex
  sources/model/global.tex
Labels: documentazione

#103 Verbale Interno 28/05
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/VerbaleInterno_2024-05-28.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/firma_interna.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/local.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-28/todo.tex
Labels: documentazione

#108 Preventivo sprint 5
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-5.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-5/distribuzione_ore_risorsa_ruolo.pdf.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-5/distribuzione_ore_ruolo.pdf.pdf
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
Labels: documentazione, responsabile

#110 Aggiornamento registro modifiche PdP
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
Labels: hotfix

#111 Spiegazione struttura repository nelle NdP
  sources/documents/2_RTB/NormeDiProgetto/Supporto/gestioneconfigurazione.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#112 Completata spiegazione funzionamento foglio di calcolo condiviso [NdP]
  sources/documents/2_RTB/NormeDiProgetto/Primari/fornitura.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#113 Aggiunta sezione pull request nelle NdP
  sources/documents/2_RTB/NormeDiProgetto/Supporto/gestioneconfigurazione.tex
  sources/documents/2_RTB/NormeDiProgetto/introduzione.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#119 corretto comando avvio per rimuovere warning
  tools/docker-compose.yml
Labels: bug, programmatore

#114 Ampliamento AdR [casi d'uso, grafici e requisiti]
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc10.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc12.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc2.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc27.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc3.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc5.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc7.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc8.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc9.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc9_1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/casiduso.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/introduzione.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc1.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc10.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc12.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc18.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc2.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc26.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc27.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc28.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc3.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc4.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc5.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc6.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc7.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc8.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc9.tex
  sources/model/global.tex
Labels: documentazione, analista

#117 Espansione PdQ grafici
  sources/documents/2_RTB/PianoDiQualifica/PianoDiQualifica.tex
  sources/documents/2_RTB/PianoDiQualifica/assets/frequenza_pull_request.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/rischi_inattesi.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/variazione_costo.pdf
  sources/documents/2_RTB/PianoDiQualifica/cruscotto_valutazione.tex
  sources/documents/2_RTB/PianoDiQualifica/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M2.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M3.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/frequenza_pull_request.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/rischi_inattesi.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/variazione_di_costo.tex
  sources/model/global.tex
Labels: documentazione

#115 Aggiornato preventivo "a finire" sprint 3
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiProgetto/stima_temporale.tex
  sources/model/global.tex
Labels: documentazione

#116 Aggiornata pianificazione futura sprint 3
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione

#104 Verbale interno 2024-06-03
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/VerbaleInterno_2024-06-03.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/firma_interna.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/local.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/todo.tex
  sources/model/modelassets/signatures/firma_martina.png
Labels: documentazione

#122 Modificato uc25 con Visualizzazione singolo messaggio e sottocasi d'uso
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc25.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/uc25_1.png
  sources/documents/2_RTB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc25.tex
  sources/model/global.tex
Labels: documentazione, analista

#124 Grafico e metrica
  sources/documents/2_RTB/PianoDiQualifica/PianoDiQualifica.tex
  sources/documents/2_RTB/PianoDiQualifica/assets/frequenza_pull_request.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/stabilità_requisiti.pdf
  sources/documents/2_RTB/PianoDiQualifica/assets/variazione_costo.pdf
  sources/documents/2_RTB/PianoDiQualifica/cruscotto_valutazione.tex
  sources/documents/2_RTB/PianoDiQualifica/tabelle_M2.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/frequenza_pull_request.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/stabilità_requisiti.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/variazione_di_costo.tex
Labels: documentazione, amministratore

#127 Preventivo sprint 6
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Pianificazione/pianificazione.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-6.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-6/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-6/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: responsabile

#131 Feature misurazione m.2.2
  sources/documents/2_RTB/PianoDiQualifica/assets/variazione_task_completati.pdf
  sources/documents/2_RTB/PianoDiQualifica/cruscotto_valutazione.tex
  sources/documents/2_RTB/PianoDiQualifica/valutazionemetriche/variazione_task_completati.tex
Labels: documentazione, amministratore

#129 Glossario (termini e definizioni)
  sources/documents/2_RTB/Glossario/Lettere/a.tex
  sources/documents/2_RTB/Glossario/Lettere/b.tex
  sources/documents/2_RTB/Glossario/Lettere/c.tex
  sources/documents/2_RTB/Glossario/Lettere/d.tex
  sources/documents/2_RTB/Glossario/Lettere/e.tex
  sources/documents/2_RTB/Glossario/Lettere/f.tex
  sources/documents/2_RTB/Glossario/Lettere/g.tex
  sources/documents/2_RTB/Glossario/Lettere/h.tex
  sources/documents/2_RTB/Glossario/Lettere/i.tex
  sources/documents/2_RTB/Glossario/Lettere/j.tex
  sources/documents/2_RTB/Glossario/Lettere/k.tex
  sources/documents/2_RTB/Glossario/Lettere/l.tex
  sources/documents/2_RTB/Glossario/Lettere/m.tex
  sources/documents/2_RTB/Glossario/Lettere/n.tex
  sources/documents/2_RTB/Glossario/Lettere/o.tex
  sources/documents/2_RTB/Glossario/Lettere/p.tex
  sources/documents/2_RTB/Glossario/Lettere/q.tex
  sources/documents/2_RTB/Glossario/Lettere/r.tex
  sources/documents/2_RTB/Glossario/Lettere/s.tex
  sources/documents/2_RTB/Glossario/Lettere/t.tex
  sources/documents/2_RTB/Glossario/Lettere/u.tex
  sources/documents/2_RTB/Glossario/Lettere/v.tex
  sources/documents/2_RTB/Glossario/Lettere/w.tex
  sources/documents/2_RTB/Glossario/Lettere/x.tex
  sources/documents/2_RTB/Glossario/Lettere/y.tex
  sources/documents/2_RTB/Glossario/Lettere/z.tex
  sources/documents/2_RTB/Glossario/a.tex
  sources/documents/2_RTB/Glossario/b.tex
  sources/documents/2_RTB/Glossario/c.tex
  sources/documents/2_RTB/Glossario/d.tex
  sources/documents/2_RTB/Glossario/e.tex
  sources/documents/2_RTB/Glossario/f.tex
  sources/documents/2_RTB/Glossario/g.tex
  sources/documents/2_RTB/Glossario/h.tex
  sources/documents/2_RTB/Glossario/i.tex
  sources/documents/2_RTB/Glossario/j.tex
  sources/documents/2_RTB/Glossario/k.tex
  sources/documents/2_RTB/Glossario/l.tex
  sources/documents/2_RTB/Glossario/m.tex
  sources/documents/2_RTB/Glossario/n.tex
  sources/documents/2_RTB/Glossario/o.tex
  sources/documents/2_RTB/Glossario/p.tex
  sources/documents/2_RTB/Glossario/q.tex
  sources/documents/2_RTB/Glossario/r.tex
  sources/documents/2_RTB/Glossario/registro_modifiche.tex
  sources/documents/2_RTB/Glossario/s.tex
  sources/documents/2_RTB/Glossario/t.tex
  sources/documents/2_RTB/Glossario/u.tex
  sources/documents/2_RTB/Glossario/v.tex
  sources/documents/2_RTB/Glossario/w.tex
  sources/documents/2_RTB/Glossario/x.tex
  sources/documents/2_RTB/Glossario/y.tex
  sources/documents/2_RTB/Glossario/z.tex
Labels: documentazione
