Repository Argo-swe/Docs, pull requests merged in 2024-05, with the labels that each got.

#59 Fix verbali interni [uppercase + proper names]
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-03/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-10/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-16/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-20/todo.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/local.tex
  sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/registro_modifiche.tex
Labels: amministratore

#68 File conf [pulizia dell'output pre-generazione artefatto]
  .github/workflows/build.yml
  tools/compilescript.sh
  tools/docker/Dockerfile
  tools/docker/install-deps.sh
Labels: bug, hotfix, amministratore

#63 PdP Preventivo sprint 2
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-2/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-2/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/local.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
Labels: documentazione, responsabile

#62 Raccolta termini nel Glossario
  sources/documents/2_RTB/Glossario/Glossario.tex
  sources/documents/2_RTB/Glossario/Lettere/a.tex
  sources/documents/2_RTB/Glossario/Lettere/b.tex
  sources/documents/2_RTB/Glossario/Lettere/c.tex
  sources/documents/2_RTB/Glossario/Lettere/d.tex
  sources/documents/2_RTB/Glossario/Lettere/e.tex
  sources/documents/2_RTB/Glossario/Lettere/f.tex
  sources/documents/2_RTB/Glossario/Lettere/g.tex
  sources/documents/2_RTB/Glossario/Lettere/h.tex
  sources/documents/2_RTB/Glossario/Lettere/i.tex
  sources/documents/2_RTB/Glossario/Lettere/j.tex
  sources/documents/2_RTB/Glossario/Lettere/k.tex
  sources/documents/2_RTB/Glossario/Lettere/l.tex
  sources/documents/2_RTB/Glossario/Lettere/m.tex
  sources/documents/2_RTB/Glossario/Lettere/n.tex
  sources/documents/2_RTB/Glossario/Lettere/o.tex
  sources/documents/2_RTB/Glossario/Lettere/p.tex
  sources/documents/2_RTB/Glossario/Lettere/q.tex
  sources/documents/2_RTB/Glossario/Lettere/r.tex
  sources/documents/2_RTB/Glossario/Lettere/s.tex
  sources/documents/2_RTB/Glossario/Lettere/t.tex
  sources/documents/2_RTB/Glossario/Lettere/u.tex
  sources/documents/2_RTB/Glossario/Lettere/v.tex
  sources/documents/2_RTB/Glossario/Lettere/w.tex
  sources/documents/2_RTB/Glossario/Lettere/x.tex
  sources/documents/2_RTB/Glossario/Lettere/y.tex
  sources/documents/2_RTB/Glossario/Lettere/z.tex
  sources/documents/2_RTB/Glossario/a.tex
  sources/documents/2_RTB/Glossario/altro.tex
  sources/documents/2_RTB/Glossario/b.tex
  sources/documents/2_RTB/Glossario/c.tex
  sources/documents/2_RTB/Glossario/d.tex
  sources/documents/2_RTB/Glossario/e.tex
  sources/documents/2_RTB/Glossario/f.tex
  sources/documents/2_RTB/Glossario/g.tex
  sources/documents/2_RTB/Glossario/h.tex
  sources/documents/2_RTB/Glossario/i.tex
  sources/documents/2_RTB/Glossario/j.tex
  sources/documents/2_RTB/Glossario/l.tex
  sources/documents/2_RTB/Glossario/local.tex
  sources/documents/2_RTB/Glossario/p.tex
  sources/documents/2_RTB/Glossario/r.tex
  sources/documents/2_RTB/Glossario/registro_modifiche.tex
  sources/documents/2_RTB/Glossario/s.tex
  sources/documents/2_RTB/Glossario/t.tex
  sources/documents/2_RTB/Glossario/u.tex
  sources/documents/2_RTB/Glossario/v.tex
  sources/documents/2_RTB/Glossario/w.tex
  sources/model/global.tex
  sources/model/layout.tex
Labels: amministratore

#64 PdP consuntivo sprint 2
  sources/documents/2_RTB/Glossario/a.tex
  sources/documents/2_RTB/Glossario/altro.tex
  sources/documents/2_RTB/Glossario/b.tex
  sources/documents/2_RTB/Glossario/c.tex
  sources/documents/2_RTB/Glossario/d.tex
  sources/documents/2_RTB/Glossario/e.tex
  sources/documents/2_RTB/Glossario/f.tex
  sources/documents/2_RTB/Glossario/g.tex
  sources/documents/2_RTB/Glossario/h.tex
  sources/documents/2_RTB/Glossario/i.tex
  sources/documents/2_RTB/Glossario/j.tex
  sources/documents/2_RTB/Glossario/k.tex
  sources/documents/2_RTB/Glossario/l.tex
  sources/documents/2_RTB/Glossario/local.tex
  sources/documents/2_RTB/Glossario/m.tex
  sources/documents/2_RTB/Glossario/n.tex
  sources/documents/2_RTB/Glossario/o.tex
  sources/documents/2_RTB/Glossario/p.tex
  sources/documents/2_RTB/Glossario/q.tex
  sources/documents/2_RTB/Glossario/r.tex
  sources/documents/2_RTB/Glossario/registro_modifiche.tex
  sources/documents/2_RTB/Glossario/s.tex
  sources/documents/2_RTB/Glossario/t.tex
  sources/documents/2_RTB/Glossario/u.tex
  sources/documents/2_RTB/Glossario/v.tex
  sources/documents/2_RTB/Glossario/w.tex
  sources/documents/2_RTB/Glossario/x.tex
  sources/documents/2_RTB/Glossario/y.tex
  sources/documents/2_RTB/Glossario/z.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-2/budget_speso.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-2/copertura_oraria.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-2/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Consuntivo/Sprint-2/distribuzione_ore_ruolo.pdf
Labels: documentazione, responsabile

#57 Porting Analisi dei Requisiti e modifiche generali
  sources/documents/2_RTB/AnalisiDeiRequisiti/AnalisiDeiRequisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/assets/.gitkeep
  sources/documents/2_RTB/AnalisiDeiRequisiti/casiduso.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/descrizione.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/introduzione.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/local.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc1.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc10.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc11.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc12.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc13.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc14.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc15.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc16.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc17.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc18.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc2.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc3.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc4.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc5.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc6.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc7.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc8.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc9.tex
  sources/model/global.tex
Labels: documentazione, analista

#70 Aggiornamento NdP [dashboard google sheets]
  sources/documents/2_RTB/NormeDiProgetto/NormeDiProgetto.tex
  sources/documents/2_RTB/NormeDiProgetto/Primari/fornitura.tex
  sources/documents/2_RTB/NormeDiProgetto/local.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: amministratore

#69 Aggiornamento NdP [norme tipografiche]
  sources/documents/2_RTB/NormeDiProgetto/Supporto/documentazione.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
Labels: amministratore

#67 Aggiornamento NdP (struttura verbali e tabella Todo / In Progress)
  sources/documents/2_RTB/NormeDiProgetto/Supporto/documentazione.tex
  sources/documents/2_RTB/NormeDiProgetto/local.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: amministratore

#74 Struttura PdQ
  sources/documents/2_RTB/PianoDiQualifica/PianoDiQualifica.tex
  sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
  sources/documents/2_RTB/PianoDiQualifica/local.tex
  sources/documents/2_RTB/PianoDiQualifica/obiettivi_metrici_qualità.tex
  sources/documents/2_RTB/PianoDiQualifica/registro_modifiche.tex
Labels: documentazione, amministratore

#73 Automazione chiusura ticket [NdP]
  sources/documents/2_RTB/NormeDiProgetto/Supporto/gestioneconfigurazione.tex
  sources/documents/2_RTB/NormeDiProgetto/registro_modifiche.tex
  sources/model/global.tex
Labels: documentazione, amministratore

#75 Modifica file di configurazione [push e pull ghcr]
  .github/workflows/build.yml
Labels: task, amministratore

#66 Sezione relativa all'analisi dei rischi del PdP
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO1.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO2.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO3.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO4.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO5.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/rischi_organizzativi.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_tecnologici/rischi_tecnologici.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/analisi_rischi.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Periodi/periodo-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/local.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
Labels: documentazione, amministratore, responsabile

#76 Aggiunte sottosezioni e prime metriche [PdQ]
  sources/documents/2_RTB/PianoDiQualifica/ObiettiviQualita/qualita_obiettivo.tex
  sources/documents/2_RTB/PianoDiQualifica/ObiettiviQualita/qualita_processo.tex
  sources/documents/2_RTB/PianoDiQualifica/ObiettiviQualita/qualita_prodotto.tex
  sources/documents/2_RTB/PianoDiQualifica/PianoDiQualifica.tex
  sources/documents/2_RTB/PianoDiQualifica/obiettivi_qualita.tex
Labels: documentazione, amministratore

#79 ARGO-35-Aggiornamento-AdR
  sources/documents/2_RTB/AnalisiDeiRequisiti/casiduso.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/introduzione.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/registro_modifiche.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc1.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc10.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc11.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc12.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc14.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc15.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc16.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc18.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc19.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc2.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc3.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc4.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc5.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc6.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc7.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc8.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc9.tex
Labels: documentazione, analista

#78 Verbale interno del 7 maggio nuovo branch
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/VerbaleInterno_2024-05-07.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/firma_interna.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/local.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/todo.tex
  sources/model/modelassets/signatures/firma_tommaso.png
Labels: documentazione

#80 Aggiornamento convenzioni lettere maiuscole
  sources/documents/2_RTB/NormeDiProgetto/Supporto/documentazione.tex
Labels: documentazione, hotfix, amministratore

#84 Verbale Interno 2024-05-23
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/VerbaleInterno_2024-05-23.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/firma_interna.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/local.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/todo.tex
Labels: documentazione

#85 Modifica struttura PdP e miglioramento consuntivo
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO1.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO2.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO3.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO4.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO5.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/RO/RO6.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_organizzativi/rischi_organizzativi.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_tecnologici/RT/RT1.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/Tipologia/Rischi_tecnologici/RT/RT2.tex
  sources/documents/2_RTB/PianoDiProgetto/Analisi_rischi/analisi_rischi.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-2.tex
  sources/documents/2_RTB/PianoDiProgetto/PianoDiProgetto.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Totale/distribuzione_ore_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/introduzione.tex
  sources/documents/2_RTB/PianoDiProgetto/local.tex
  sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
  sources/documents/2_RTB/PianoDiProgetto/stima_costi.tex
  sources/documents/2_RTB/PianoDiProgetto/stima_temporale.tex
Labels: documentazione, responsabile

#88 Steso preventivo sprint 4 nel PdP
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Periodi/periodo-1.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-4.tex
  sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-4/distribuzione_ore_risorsa_ruolo.pdf
  sources/documents/2_RTB/PianoDiProgetto/assets/Preventivo/Sprint-4/distribuzione_ore_ruolo.pdf
Labels: documentazione, responsabile

#82 Prima stesura verbale esterno 2024-05-06
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-05-06/VerbaleEsterno_2024-05-06.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-05-06/assets/.gitkeep
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-05-06/capitolo-informazioni.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-05-06/capitolo-riunione.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-05-06/firma_esterna.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-05-06/local.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-05-06/registro_modifiche.tex
  sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-05-06/todo.tex
Labels: documentazione

#93 Sistemazione sottocasi UC2
  sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
  sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc2.tex
Labels: documentazione

#92 Consuntivo sprint 3 - risultati del questionario
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-3.tex
  sources/documents/2_RTB/PianoDiProgetto/Consuntivo/consuntivo.tex
Labels: documentazione
